config/routes.rb
Pancake::Application.routes.draw do
  resources :posts

  devise_for :models
  get 'clubs/index'

  root "clubs#index"

  

end

app/models/club.rb
class Club < ActiveRecord::Base
  validates :name, presence: true, length: {minimum: 3}
  has_many :users_clubs, dependent: :destroy
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :users_clubs, dependent: :destroy
  has_many :posts, through: :users_clubs
end

app/models/oss_club.rb
class OssClub < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :users_club
  validates :description, presence: true
  validates :description, length: {minimum: 3}
end

app/models/users_club.rb
class UsersClub < ActiveRecord::Base
  belongs_to :model
  belongs_to :club
  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_model!
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  def index
    @clubs = Club.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    if params[:format].nil?
      @posts = Post.all
      #@posts = Post.where(users_club_id: Model.find(current_model.id).users_club.id)
    else
      if UsersClub.where(club_id: params[:format], model_id: current_model.id).blank?
        club = Model.find(current_model.id).users_clubs.create(club_id: params[:format])
        club.posts.create(description: "<h3> Welcome to the #{Club.find(UsersClub.last.club_id).name} </h3>")
      else
        @posts = Model.find(current_model.id).users_clubs.where(club_id: params[:format]).first.posts
      end
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:users_club_id, :title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/clubs/index.html.haml
-@clubs.each do |club|
  %ul.pricing-table.span3
    %li.title
      = club.name
    %li.price= club.tagline
    %li.description= club.description
    -if club.users_clubs.where(model_id: current_model.id).length == 0
      %li.cta-button
        = link_to "Join", posts_path(club.id), class: "button" 
    -else
      %li.bullet-item
        = link_to "New Post", new_post_path(club.id), class: "button"
      %li.bullet-item
        = link_to "Show Posts", posts_path(club.id), class: "button"

app/views/layouts/application.html.haml
%html
  %head
    %title AitClubs 
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
%body
  %div.navbar.navbar-fixed-top.navbar-inverse
    %div.navbar-inner
      %div.container
        %a.brand{:href => "/"} 
          %i.icon-flag
          AitClubs
        %ul.nav.pull-right
          - if model_signed_in?
            %li
              = link_to " Home ", root_path, class: "icon-home"
            %li
              = link_to " My Posts ", posts_path, class: "icon-list"
            %li
              = link_to " #{current_model.email}", edit_model_registration_path, class: "icon-edit"
            %li
              = link_to " Sign Out ", destroy_model_session_path,method: :delete, class: "icon-off"
          - else
            %li
              = link_to " Register ",new_model_registration_path, class: "icon-list"
            %li
              = link_to " Login ",new_model_session_path, class: "icon-user"

  %div.container.some{style:"padding-top: 5%;"}
    - if notice
      .alert.alert-success.some{align: 'center'}
        %strong= notice
    - if alert
      .alert.alert-error.some{align: 'center'}
        = alert
    = yield
  %div.navbar.navbar-fixed-bottom
    %div.navbar-inner
      %div.container
      %h6{align: "center"} 
        Designed and built by
        %a{href: "https://twitter.com/pkrawat1"}
          @pankaj
        and
        %a{href: "https://twitter.com/vjdhama"}
          @vjdhama

app/views/posts/_form.html.haml
= form_for @post, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    .controls
      = f.text_field :users_club_id, :class => 'text_field hide', value: UsersClub.where(club_id: params[:format], model_id: current_model.id).first.id
  .control-group
    = f.label :title, :class => 'control-label'
    .controls
      = f.text_field :title, :class => 'text_field'
  .control-group
    = f.label :description, :class => 'control-label'
    .controls
      = f.text_field :description
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), posts_path, :class => 'btn'

app/views/posts/edit.html.haml
.well
  - model_class = Post
  .page-header
    %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
  = render :partial => "form"

app/views/posts/index.html.haml
.well
  .page-header
    - if params[:format].nil?
      %h1 All Posts
    - else
      %h1= Club.find(params[:format]).name 
    = link_to "New Post", new_post_path(@posts.first.users_club.club_id), class: "btn btn-info" if !params[:format].nil?
  - @posts.reverse.each do |post|
    .status
      %strong= post.users_club.model.email
      %br
      -if !post.title.blank?
        %strong
          Title : 
          = post.title
      %p= post.description
      .meta
        = link_to " Edit ", edit_post_path(post), class: "icon-pencil"
        = link_to " Delete ", post_path(post), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, class: "icon-remove"
        = link_to "   " + time_ago_in_words(post.created_at) + " ago", post, class: "icon-time"

app/views/posts/new.html.haml
.well
  - model_class = Post
  .page-header
    %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
  = render :partial => "form"

app/views/posts/show.html.haml
.well
  - model_class = Post
  .page-header
    %h1=t '.title', :default => model_class.model_name.human.titleize
  %p
    %strong= model_class.human_attribute_name(:title) + ':'
    %br
    = @post.title
  %p
    %strong= model_class.human_attribute_name(:description) + ':'
    %br
    = @post.description

  .form-actions
    = link_to t('.back', :default => t("helpers.links.back")), posts_path, :class => 'btn'
    = link_to t('.edit', :default => t("helpers.links.edit")), edit_post_path(@post), :class => 'btn'
    = link_to t('.destroy', :default => t("helpers.links.destroy")), post_path(@post), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'